### ISSUE TITLE
Mqtt() object with self.app = None when using init_app() method

### ISSUE THREAD

**Issue by pg-goose** [stlehmann/Flask-MQTT#121]
I had issues dealing with application context and I realized that the `app` member of the `Mqtt` class stays `None` when initializing it the following way.

```
client = Mqtt()
# ···
client.init_app(flask_app)
```
if I assign it after `init_app(flask_app)` I can solve my context problems. Is there a reason for this? if not I think it should be enough with adding:

```
class Mqtt:
    def init_app(self, app: Flask) -> None:
        """Init the Flask-MQTT addon."""
        if app is None:
            self.app = app
# ···
```

I've never contributed to any repo so I'm not sure about the proper process, sorry.

**Comment by Undertone0809** [comment]
I don't think it is a good way to solve the problem. You should init the mqtt client config when you build it. So the code style can can follow Flask.

When you init the Flask, your code must as follows:
```python
app = Flask(__name__)
```

When you see source code of the `class Flask`. You can see inject the import_name is necessary when you do work of init. So does Mqtt.
![image](https://user-images.githubusercontent.com/72488598/211213080-36036cfc-5d45-4b85-a796-8958ecee8764.png)


Actually, you can init the mqtt client if you don't injection falsk app as follows. It's also a way to init the mqtt. But this code implementation is definitely not the way the author wants to see development. The work of mqtt init should finish by `flask_mqtt` rather than user.
```python
app = Flask(__name__)
mqtt = Mqtt()
mqtt.app = Flask
mqtt.init_app(app)
```
